/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SwipeRouteImport } from './routes/swipe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SampleReportRouteImport } from './routes/sample-report'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NamesSlugRouteImport } from './routes/names.$slug'
import { Route as JoinCodeRouteImport } from './routes/join.$code'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SwipeRoute = SwipeRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleReportRoute = SampleReportRouteImport.update({
  id: '/sample-report',
  path: '/sample-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NamesSlugRoute = NamesSlugRouteImport.update({
  id: '/names/$slug',
  path: '/names/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/matches': typeof MatchesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/sample-report': typeof SampleReportRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swipe': typeof SwipeRoute
  '/terms': typeof TermsRoute
  '/join/$code': typeof JoinCodeRoute
  '/names/$slug': typeof NamesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/matches': typeof MatchesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/sample-report': typeof SampleReportRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swipe': typeof SwipeRoute
  '/terms': typeof TermsRoute
  '/join/$code': typeof JoinCodeRoute
  '/names/$slug': typeof NamesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/matches': typeof MatchesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/sample-report': typeof SampleReportRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swipe': typeof SwipeRoute
  '/terms': typeof TermsRoute
  '/join/$code': typeof JoinCodeRoute
  '/names/$slug': typeof NamesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/explore'
    | '/matches'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/report'
    | '/sample-report'
    | '/saved'
    | '/sitemap.xml'
    | '/swipe'
    | '/terms'
    | '/join/$code'
    | '/names/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/matches'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/report'
    | '/sample-report'
    | '/saved'
    | '/sitemap.xml'
    | '/swipe'
    | '/terms'
    | '/join/$code'
    | '/names/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/explore'
    | '/matches'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/report'
    | '/sample-report'
    | '/saved'
    | '/sitemap.xml'
    | '/swipe'
    | '/terms'
    | '/join/$code'
    | '/names/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRoute
  MatchesRoute: typeof MatchesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReportRoute: typeof ReportRoute
  SampleReportRoute: typeof SampleReportRoute
  SavedRoute: typeof SavedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SwipeRoute: typeof SwipeRoute
  TermsRoute: typeof TermsRoute
  JoinCodeRoute: typeof JoinCodeRoute
  NamesSlugRoute: typeof NamesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swipe': {
      id: '/swipe'
      path: '/swipe'
      fullPath: '/swipe'
      preLoaderRoute: typeof SwipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-report': {
      id: '/sample-report'
      path: '/sample-report'
      fullPath: '/sample-report'
      preLoaderRoute: typeof SampleReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/names/$slug': {
      id: '/names/$slug'
      path: '/names/$slug'
      fullPath: '/names/$slug'
      preLoaderRoute: typeof NamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRoute,
  MatchesRoute: MatchesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRoute,
  SampleReportRoute: SampleReportRoute,
  SavedRoute: SavedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SwipeRoute: SwipeRoute,
  TermsRoute: TermsRoute,
  JoinCodeRoute: JoinCodeRoute,
  NamesSlugRoute: NamesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
